extends:
    - airbnb-base
    - plugin:flowtype/recommended
    - prettier
parser: babel-eslint
root: true
plugins:
    - flowtype
    - import
    - prettier
    - chai-friendly
    - mocha
env: 
    node: true
    mocha: true
rules:
    quotes:
        - error
        - "double"
    semi:
        - error
        - "never"
    class-methods-use-this: 0
    prettier/prettier:
        - error
        - semi: false
          trailingComma: all
    flowtype/no-primitive-constructor-types: 2
    flowtype/no-dupe-keys: 2
    mocha/no-exclusive-tests: error
    # Let Prettier take care of the following rules
    comma-dangle: 0
    arrow-parens: 0
    object-curly-newline: 0
    object-curly-spacing: 0
        
